### PR TITLE
Add initial tab structure

### PR DESCRIPTION
**Pull request by andywaltlova**
RSPEED-157

### CODE REVIEW

**Comment by andywaltlova** [comment]
[dr-load-tabs-local.webm](https://github.com/user-attachments/assets/567f5440-742c-4e4d-b8e0-471d44de4262)

**Comment by andywaltlova** [comment]
Ready for review, CI is failing because of codecov

**Comment by andywaltlova** [comment]
[1-DR-frontend.webm](https://github.com/user-attachments/assets/5efbe322-a415-4442-ad58-b190918dadda)

Up to date visual

**Comment by andywaltlova** [comment]
[Screencast from 2024-10-22 17-06-31.webm](https://github.com/user-attachments/assets/9d7db8d5-19aa-4cc4-88f1-03fc8c88b85b)

^ Latest update, no int errors, build fial is expected, merging

**Review by hosekadam — APPROVED** [review]

**Pull request merged**
